source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MultiPicker_Example', :exclusive => true do
  pod "MultiPicker", :path => "../"
end

target 'MultiPicker_Tests', :exclusive => true do
  pod "MultiPicker", :path => "../"

  
end
